### ISSUE TITLE
Refactoring/Enhancement: Store Product Page

### ISSUE THREAD

**Issue by billychen0894** [billychen0894/florist-ecommerce-app#81]
### Overview

- Objective: To enhance performance for the product page
- Motivation: To reduce disruption for users exploration on products

### Implementation Checklist

- [x]  Task 1: Refactor Product List & Pagination
- [x] Task 2: Remove redundant products fetch calls
- [x] Task 3: Refactor `Sort` component
- [x] Task 4: Refactor `Filter` component

### Disclaimer
_This issue is used for tracking purposes and to document the progress and improvements made to the project. It will remain open to allow easy access and visibility of the ongoing enhancements/refactoring efforts. Comments in this issue will be updated regularly to reflect progress and any additional improvements._

**Comment by billychen0894** [comment]
### Task 1: Refactor Product List & Pagination

The Product List and Pagination components were improved by using some helper functions to abstract away some logics, such as `constructURL()`. And the state required for Product List and Pagination are passed from the parent component.

### Related commits

- [cb8ea26](https://github.com/billychen0894/florist-ecommerce-app/commit/cb8ea2644513720f4cdaa85a66a64b74c171ab16)
- [d9fc197](https://github.com/billychen0894/florist-ecommerce-app/commit/d9fc197055b470faaa0eb97fe608594f39cee1b7)

**Comment by billychen0894** [comment]
### Task 2: Remove redundant products fetch calls

Previously, the `ProductList` and `Pagination` component were calling `fetchProducts()` individually, which is redundant. Because both components share the same data. That is, the fetch call should only be happened at the parent component of `ProductList` and `Pagination`. Once the products data is received, it then be passed down to the components.

### Related commits

- [31bafcc](https://github.com/billychen0894/florist-ecommerce-app/commit/31bafcc08a2e296738271a432cf6b37cb425acfa)
- [cb8ea26](https://github.com/billychen0894/florist-ecommerce-app/commit/cb8ea2644513720f4cdaa85a66a64b74c171ab16)

**Comment by billychen0894** [comment]
### Task 3: Refactor Sort component

Most logic for `Sort` component was abstracted away by creating helper functions, such as `getCurrSortLabel()` and `createQueryString()` to update sort related query params in the url.

### Related commits

- [fe62ed2](https://github.com/billychen0894/florist-ecommerce-app/commit/fe62ed288ba7d2448e6d509a45f846887aa6cb76)

**Comment by billychen0894** [comment]
### Task 4: Refactor Filter component

`Filter` components are utilizing SSR and CSR. The parent component is SSR that fetches required data and then further pass data down to client-side rendering components. The `FilterActionButton` and `FilterForm` are client-side rendering and both of them shared the same state. Therefore, it is easier to manage both state and data required from their parent component, using Context API.

### Related commits

- [bb49bba](https://github.com/billychen0894/florist-ecommerce-app/commit/bb49bba5062727fd74295530f000e8a291300c49)
- [21067d3](https://github.com/billychen0894/florist-ecommerce-app/commit/21067d36f9a040be7aa70e79108ef8e47188fe2c)
- [d049d1f](https://github.com/billychen0894/florist-ecommerce-app/commit/d049d1f61d82cef6b47346d92391c06b95b0b214)
